### ISSUE TITLE
Nightwatch tests are erroring

### ISSUE THREAD

**Issue by mdial89f** [CMSgov/macpro-quickstart-serverless#109]
They are erroring, not failing.
Unsure of the issue, but it's consistent behavior.
See:  https://github.com/CMSgov/macpro-quickstart-serverless/runs/1920061278?check_suite_focus=true as an example.

```
[First Test] Test Suite
=======================
- Connecting to localhost on port 9515...

⚠ Error connecting to localhost on port 9515.
_________________________________________________

TEST FAILURE: 1 error during execution; 0 tests failed, 0 passed (3.116s)

 ✖ firstTest
   An error occurred while retrieving a new session: "session not created: This version of ChromeDriver only supports Chrome version 86"
Error: An error occurred while retrieving a new session: "session not created: This version of ChromeDriver only supports Chrome version 86"
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

  Error: An error occurred while retrieving a new session: "session not created: This version of ChromeDriver only supports Chrome version 86"
       at endReadableNT (_stream_readable.js:1241:12)
       at processTicksAndRejections (internal/process/task_queues.js:84:21)

   SKIPPED:
   - My first test case
  ```

AC:
- The nightwatch tests succeed.

**Comment by mdial89f** [comment]
Allowing for chromedriver >=86.0.0 and regenerating the yarn.lock fixed this.
Will close with #89
